# https://hub.docker.com/_/microsoft-dotnet-runtime
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

COPY . .
WORKDIR "/src/MBW.BlueRiiot2MQTT/"
RUN dotnet publish -c release -o /app

# Final
FROM mcr.microsoft.com/dotnet/runtime:7.0-jammy-arm32v7
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "MBW.BlueRiiot2MQTT.dll"]