name: Docker (dev) build and push

on:
  push:
    branches: [ master, feature/auto-contents ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Dotenv Action
      uses: xom9ikk/dotenv@v1.0.2

    - name: Test
      run: "[ -f .ci-skip-tests ] && echo 'Skipping tests' || dotnet test --configuration Release"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_KEY }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: ${{ env.DOCKER_PLATFORMS }}
        push: true
        tags: ${{ env.DOCKER_TAG }}:dev
        file: ${{ env.DOCKER_DOCKERFILE }}