name: Docker (dev) build and push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Prep docker experimentals
      run: echo "DOCKER_CLI_EXPERIMENTAL=enabled" >> $GITHUB_ENV
    
    - name: Prep GIT_TAG
      run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - uses: actions/checkout@v2
    
    - name: Dotenv Action
      uses: xom9ikk/dotenv@v1.0.2
  
    - name: Build
      run: |
        [ -f "${DOCKER_DOCKERFILE}.amd64" ] && docker build -f ${DOCKER_DOCKERFILE}.amd64 -t ${DOCKER_TAG}:amd64-dev .
        [ -f "${DOCKER_DOCKERFILE}.armv7" ] && docker build -f ${DOCKER_DOCKERFILE}.armv7 -t ${DOCKER_TAG}:armv7-dev .
        [ -f "${DOCKER_DOCKERFILE}.aarch64" ] && docker build -f ${DOCKER_DOCKERFILE}.aarch64 -t ${DOCKER_TAG}:aarch64-dev .
    
    - name: Push base images to docker hub
      run: |
        echo ${{ secrets.DOCKER_KEY }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        
        [ -f "${DOCKER_DOCKERFILE}.amd64" ] && docker push ${DOCKER_TAG}:amd64-dev
        [ -f "${DOCKER_DOCKERFILE}.armv7" ] && docker push ${DOCKER_TAG}:armv7-dev
        [ -f "${DOCKER_DOCKERFILE}.aarch64" ] && docker push ${DOCKER_TAG}:aarch64-dev
      
    - name: Create manifest images + tag images
      run: |
        # Note: Manifests are created from tags from docker.io, so we must push first, then create manifest, then push again
        PARTS=''
        [ -f "${DOCKER_DOCKERFILE}.amd64" ] && PARTS="$PARTS ${DOCKER_TAG}:amd64-dev"
        [ -f "${DOCKER_DOCKERFILE}.armv7" ] && PARTS="$PARTS ${DOCKER_TAG}:armv7-dev"
        [ -f "${DOCKER_DOCKERFILE}.aarch64" ] && PARTS="$PARTS ${DOCKER_TAG}:aarch64-dev"
        
        docker manifest create ${DOCKER_TAG}:dev $PARTS
        
        docker manifest push ${DOCKER_TAG}:dev